const {sequelize} = require('../index');
const {DataTypes} = require('sequelize');
const { Userphoto } = require('./userphotos.model');

const Userprofile = sequelize.define('userprofile',{
    id:{
        type:DataTypes.INTEGER,
        primaryKey:true,
        autoIncrement:true,
    },
    userphoto:{
       type:DataTypes.INTEGER,
       references:{
        model:Userphoto,
        key:'id'
       },
       allowNull:true
    },
    profilefor:{
        type:DataTypes.STRING,
        allowNull:true
    },
    fullname:{
        type:DataTypes.STRING,
        allowNull:true
    },
    city:{
        type:DataTypes.STRING,
        allowNull:true
    },
    dateofbirth:{
        type:DataTypes.DATE,
        allowNull:true
    },
    education:{
        type:DataTypes.STRING,
        allowNull:true
    },
    bloodgroup:{
        type:DataTypes.STRING,
        allowNull:true
    },
    spectacles:{
        type:DataTypes.STRING,
        allowNull:true
    },
    gotra:{
        type:DataTypes.STRING,
        allowNull:true
    },
    birthplace:{
        type:DataTypes.STRING,
        allowNull:true
    },
    occupation:{
        type:DataTypes.STRING,
        allowNull:true
    },
    maritalstatus:{
        type:DataTypes.STRING,
        allowNull:true
    },
    height:{
        type:DataTypes.BIGINT,
        allowNull:true
    },
    occupationcity:{
        type:DataTypes.STRING,
        allowNull:true
    },
    complexion:{
        type:DataTypes.STRING,
        allowNull:true
    },
    mangal:{
        type:DataTypes.STRING,
        allowNull:true
    },
    residentcity:{
        type:DataTypes.STRING,
        allowNull:true
    },
    fathername:{
        type:DataTypes.STRING,
        allowNull:true
    },
    mothername:{
        type:DataTypes.STRING,
        allowNull:true
    },
    maternaluncle:{
        type:DataTypes.STRING,
        allowNull:true
    },
    nativeplace:{
        type:DataTypes.STRING,
        allowNull:true
    },
    citywealth:{
        type:DataTypes.STRING,
        allowNull:true
    },
    parentcity:{
        type:DataTypes.STRING,
        allowNull:true
    },
    sister:{
        type:DataTypes.STRING,
        allowNull:true
    },
    agedifference:{
        type:DataTypes.STRING,
        allowNull:true
    },
    preferredcity:{
        type:DataTypes.STRING,
        allowNull:true
    },
    expectedheight:{
        type:DataTypes.STRING,
        allowNull:true
    },
    herhiseducation:{
        type:DataTypes.STRING,
        allowNull:true
    },
    herhisoccupation:{
        type:DataTypes.STRING,
        allowNull:true
    },
    herhisparentresidence:{
        type:DataTypes.STRING,
        allowNull:true
    },
    email:{
        type:DataTypes.STRING,
        allowNull:true
    },
    mobile:{
        type:DataTypes.STRING,
        allowNull:true
    },
    userId:{
        type:DataTypes.INTEGER,
        allowNull:true
    }
})

module.exports = {Userprofile}
